### ISSUE TITLE
apl command without options does nothing

### ISSUE THREAD

**Issue by KaiserPhemi** [IAMOTZ/andela-portal-cmd#3]
#### Nitpick
Just installed the tool but noticed when the `apl` command was issued **without options**, it does nothing. 

#### Expected Behaviour
I was expecting the command to output the help menu if options weren't specified.

<img width="565" alt="screen shot 2018-11-19 at 11 26 38 am" src="https://user-images.githubusercontent.com/26272628/48701386-ab17af00-ebee-11e8-8ab3-6842422e1a03.png">

**Comment by IAMOTZ** [comment]
Hi @KaiserPhemi 
Thanks for reporting this issue and yes, it's a valid one. The help menu should show when the `apl` command is used without any option. 
 
A pull request would be raised to fix this issue the soonet. However, I would still leave this issue open until the fix is implemented.

Thanks again.

**Comment by IAMOTZ** [comment]
A pull request(#4) has been raised and merged to fix this issue, consequently, I would be closing this issue.
